# Generated by Django 4.2.4 on 2023-09-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='preço',
            new_name='preco',
        ),
    ]
